### ISSUE TITLE
Ability to parse UUID

### ISSUE THREAD

**Issue by deby22** [mongkok/fastapi-debug-toolbar#15]
https://github.com/mongkok/fastapi-debug-toolbar/blob/3552b0bbb8e1a86a4f5eaaf214e6916d52c941ef/debug_toolbar/panels/sql.py#L120-L121

Using UUID field raise an exception

`
*** TypeError: Object of type UUID is not JSON serializable
`

I suggest, adding UUID serialization, by cast to str
```
if isinstance(obj, UUID):
    return str(obj)
```
Or allow setting encoder on json.dumps method

**Comment by florimondmanca** [comment]
For anyone finding this issue, I bumped into the same situation and managed to find a workaround using FastAPI's `jsonable_encoder`:

```python
from debug_toolbar.panels.sqlalchemy import SQLAlchemyPanel as Base
from fastapi.encoders import jsonable_encoder

class SQLAlchemyPanel(Base):
    def after_execute(self, *args) -> None:  # type: ignore
        # HACK: base SQL panel calls json.dumps(parameters) at some point.
        # Ensure values such as UUIDs can be dumped.
        parameters = args[3]
        args = (*args[:3], jsonable_encoder(parameters), *args[4:])
        return super().after_execute(*args)
```

It can then be used by passing `panels=["path.to.panels.SQLAlchemyPanel"]`.

**Comment by mongkok** [comment]
Hey @deby22 , issue is fixed using `jsonable_encoder()` as suggested by @florimondmanca , see #23 and [v0.3.0](https://github.com/mongkok/fastapi-debug-toolbar/releases/tag/0.3.0).
