### ISSUE TITLE
error when connecting TortoisePanel

### ISSUE THREAD

**Issue by slipperss** [mongkok/fastapi-debug-toolbar#17]
![image](https://user-images.githubusercontent.com/94642389/189540526-d63fd090-b828-4197-9244-9cfd80beaa47.png)
![image](https://user-images.githubusercontent.com/94642389/189540607-90f950a1-a390-433f-a9b7-edc2cbd2917f.png)

**Comment by takashi-yoneya** [comment]
Perhaps the same technique as SQLAlchemy can be used.
Please refer to my response.
https://github.com/mongkok/fastapi-debug-toolbar/issues/16
