### ISSUE TITLE
Cannot upgrade to Fastapi 0.95.0

### ISSUE THREAD

**Issue by integrajerome** [mongkok/fastapi-debug-toolbar#30]
Hello,
An error occurs after upgrading to Fastapi 0.95.0.
Can someone fix this bug or share a workaround please?

<img width="877" alt="image" src="https://user-images.githubusercontent.com/91475647/226322629-b4e00922-6218-4671-bd18-d9fc5e2ffb63.png">

Best regards.

**Comment by fsecada01** [comment]
I have a pull request pending to address this. Starlette changed the name for the argument: https://github.com/mongkok/fastapi-debug-toolbar/pull/31

**Comment by mongkok** [comment]
Hi @integrajerome @fsecada01,
I'm sorry for the delay in my response.
The issue is fixed, please test the new release.

**Comment by integrajerome** [comment]
@mongkok after upgrade i cannot there is no error but i cannot download statics (404).
maybe it is because of my environment (docker).

**Comment by integrajerome** [comment]
> @mongkok after upgrade i cannot there is no error but i cannot download statics (404). maybe it is because of my environment (docker).

Actually it is because i mounted a folder on / :s
