### ISSUE TITLE
Cannot Import name 'render_stacktrace' from 'debug_toolbar.utils'

### ISSUE THREAD

**Issue by Anihouvi** [mongkok/fastapi-debug-toolbar#37]
from debug_toolbar.utils import render_stacktrace
ImportError: cannot import name 'render_stacktrace' from 'debug_toolbar.utils' (/Users/venv/lib/python3.9/site-packages/debug_toolbar/utils.py)

Having the following issue:
ORM: tortoise
DB: postgresql
python version: 3.9
fastapi  0.104.0

**Comment by mongkok** [comment]
Hey @Anihouvi , there is no `render_stacktrace` import here, maybe you installed a Django debug toolbar version.
I close the issue, if you have any questions please let me know.
