### ISSUE TITLE
ImportError: cannot import name 'AsyncExitStack' from 'fastapi.concurrency'

### ISSUE THREAD

**Issue by MarchenkoRoman** [mongkok/fastapi-debug-toolbar#40]
fastapi >=0.106 has breaking changes, was removed AsyncExitStack from concurrency

To Fix:
change import 
from fastapi.concurrency import AsyncExitStack
to:
from contextlib import AsyncExitStack

**Comment by fsecada01** [comment]
@MarchenkoRoman Can you create a PR?

**Comment by mongkok** [comment]
Thanks @MarchenkoRoman , the issue is fixed, please check the new release.
